
// This is a partial list. In a real app, this would come from a database.
// The descriptions and other details will be generated by the AI.
export const schemes = [
  {
    id: "pm-kisan",
    category: "Central",
    state: "All India",
    lastUpdated: "2024-12-15",
    contact: {
      department: "Ministry of Agriculture and Farmers Welfare",
      phone: "155261 / 011-24300606",
      email: "pmkisan-ict@gov.in"
    },
    website: "https://pmkisan.gov.in"
  },
  {
    id: "pmfby",
    category: "Central",
    state: "All India",
    lastUpdated: "2024-11-30",
    contact: {
      department: "Ministry of Agriculture and Farmers Welfare",
      phone: "1800-180-1551",
      email: "help.agri-insurance@gov.in"
    },
    website: "https://pmfby.gov.in"
  },
  {
    id: "soil-health-card",
    category: "Central",
    state: "All India",
    lastUpdated: "2024-10-25",
    contact: {
      department: "Department of Agriculture, Cooperation & Farmers Welfare",
      phone: "1800-180-1551",
      email: "soilhealth@gov.in"
    },
    website: "https://soilhealth.dac.gov.in/"
  },
  {
    id: "kcc",
    category: "Central",
    state: "All India",
    lastUpdated: "2024-11-20",
    contact: {
      department: "NABARD / Ministry of Agriculture and Farmers Welfare",
      phone: "1800-532-7444 (UMANG)",
      email: "contact@nabard.org"
    },
    website: "https://www.nabard.org"
  },
  {
    id: "enam",
    category: "Central",
    state: "All India",
    lastUpdated: "2024-12-01",
    contact: {
      department: "Small Farmers’ Agribusiness Consortium (SFAC)",
      phone: "1800-270-0224",
      email: "enam.helpdesk@gmail.com"
    },
    website: "https://enam.gov.in"
  },
  {
    id: "ysr-rythu-bharosa",
    category: "State",
    state: "Andhra Pradesh",
    lastUpdated: "2024-12-10",
    contact: {
      department: "Department of Agriculture, Govt. of Andhra Pradesh",
      phone: "1902",
      email: "ysrrythubharosa@ap.gov.in"
    },
    website: "https://ysrrythubharosa.ap.gov.in/"
  },
  {
    id: "ap-zero-interest-loan",
    category: "State",
    state: "Andhra Pradesh",
    lastUpdated: "2024-10-20",
    contact: {
      department: "Agriculture and Cooperation Department, AP",
      phone: "1800-425-4440",
      email: "agricoop@ap.gov.in"
    },
    website: "https://www.google.com/search?q=AP+Zero+Interest+Crop+Loan+Scheme"
  },
  {
    id: "arunachal-sashakt-kisan",
    category: "State",
    state: "Arunachal Pradesh",
    lastUpdated: "2024-09-30",
    contact: {
      department: "Department of Agriculture, Govt. of Arunachal Pradesh",
      phone: "0360-2212352",
      email: "agri.arunachal@gmail.com"
    },
    website: "https://www.google.com/search?q=Chief+Minister’s+Sashakt+Kisan+Yojana+Arunachal+Pradesh"
  },
  {
    id: "assam-cmsguy",
    category: "State",
    state: "Assam",
    lastUpdated: "2024-11-15",
    contact: {
      department: "Assam Agriculture Department",
      phone: "1800-345-1100",
      email: "cmsguyassam@gmail.com"
    },
    website: "https://www.google.com/search?q=Chief+Minister’s+Samagra+Gramya+Unnayan+Yojana+CMSGUY"
  },
  {
    id: "assam-apart",
    category: "State",
    state: "Assam",
    lastUpdated: "2024-10-05",
    contact: {
      department: "Assam Rural Infrastructure & Agricultural Services Society (ARIAS)",
      phone: "0361-2332125",
      email: "apart.arias@gmail.com"
    },
    website: "https://arias.in/apart/"
  },
  {
    id: "bihar-fasal-sahayata",
    category: "State",
    state: "Bihar",
    lastUpdated: "2024-11-25",
    contact: {
      department: "Department of Agriculture, Government of Bihar",
      phone: "1800-180-1551",
      email: "agribiharhelpdesk@gmail.com"
    },
    website: "https://dbtagriculture.bihar.gov.in"
  },
  {
    id: "bihar-diesel-anudan",
    category: "State",
    state: "Bihar",
    lastUpdated: "2024-08-10",
    contact: {
      department: "Agriculture Department, Bihar",
      phone: "1800-180-1551",
      email: "agribiharhelpdesk@gmail.com"
    },
    website: "https://dbtagriculture.bihar.gov.in"
  },
  {
    id: "goa-kamdhenu",
    category: "State",
    state: "Goa",
    lastUpdated: "2024-08-25",
    contact: {
      department: "Directorate of Animal Husbandry & Veterinary Services, Goa",
      phone: "0832-2437245",
      email: "dir-ahvs.goa@nic.in"
    },
    website: "https://www.google.com/search?q=Kamdhenu+Scheme+Goa"
  },
  {
    id: "goa-agri-machinery",
    category: "State",
    state: "Goa",
    lastUpdated: "2024-09-12",
    contact: {
      department: "Department of Agriculture, Goa",
      phone: "0832-2227781",
      email: "agri.goa@nic.in"
    },
    website: "https://www.google.com/search?q=Assistance+for+Purchase+of+Agricultural+Machinery+Goa"
  },
  {
    id: "gujarat-kisan-parivahan",
    category: "State",
    state: "Gujarat",
    lastUpdated: "2024-09-30",
    contact: {
      department: "Department of Agriculture, Gujarat",
      phone: "1800-233-5500",
      email: "agri-info@gujarat.gov.in"
    },
    website: "https://ikhedut.gujarat.gov.in"
  },
  {
    id: "gujarat-micro-irrigation",
    category: "State",
    state: "Gujarat",
    lastUpdated: "2024-10-05",
    contact: {
      department: "Gujarat Green Revolution Company Ltd (GGRC)",
      phone: "1800-233-5500",
      email: "support@ggrc.co.in"
    },
    website: "https://ikhedut.gujarat.gov.in"
  },
  {
    id: "haryana-mera-pani-meri-virasat",
    category: "State",
    state: "Haryana",
    lastUpdated: "2024-07-30",
    contact: {
      department: "Department of Agriculture and Farmers Welfare, Haryana",
      phone: "1800-180-2117",
      email: "agrifw@hry.nic.in"
    },
    website: "https://agriharyana.gov.in"
  },
  {
    id: "haryana-bhavantar-bharpai",
    category: "State",
    state: "Haryana",
    lastUpdated: "2024-10-10",
    contact: {
      department: "Department of Agriculture, Haryana",
      phone: "1800-180-2060",
      email: "mfmb-support@hry.gov.in"
    },
    website: "https://fasal.haryana.gov.in/"
  },
  {
    id: "hp-krishi-utpad-sarankshan",
    category: "State",
    state: "Himachal Pradesh",
    lastUpdated: "2024-08-15",
    contact: {
      department: "Department of Agriculture, Himachal Pradesh",
      phone: "0177-2623835",
      email: "agr-hp@nic.in"
    },
    website: "https://www.google.com/search?q=Krishi+Utpad+Sarankshan+Yojana+Himachal+Pradesh"
  },
  {
    id: "hp-khet-sanrakshan",
    category: "State",
    state: "Himachal Pradesh",
    lastUpdated: "2024-09-20",
    contact: {
      department: "Agriculture Department, Himachal Pradesh",
      phone: "0177-2882414",
      email: "agri.hp@nic.in"
    },
    website: "https://www.google.com/search?q=Mukhyamantri+Khet+Sanrakshan+Yojana+Himachal+Pradesh"
  },
  {
    id: "jharkhand-fasal-rahat",
    category: "State",
    state: "Jharkhand",
    lastUpdated: "2024-05-01",
    contact: {
      department: "Department of Agriculture, Cooperation and Farmers Welfare, Jharkhand",
      phone: "1800-180-1551",
      email: "--"
    },
    website: "https://jrfry.jharkhand.gov.in/"
  },
  {
    id: "jharkhand-krishi-ashirwad",
    category: "State",
    state: "Jharkhand",
    lastUpdated: "2020-04-01",
    contact: {
      department: "Department of Agriculture, Jharkhand",
      phone: "1800-180-1551",
      email: "--"
    },
    website: "https://www.google.com/search?q=Mukhya+Mantri+Krishi+Ashirwad+Yojana"
  },
  {
    id: "jharkhand-rin-mafi",
    category: "State",
    state: "Jharkhand",
    lastUpdated: "2024-02-01",
    contact: {
      department: "Department of Finance and Agriculture, Jharkhand",
      phone: "--",
      email: "--"
    },
    website: "https://jkrny.jharkhand.gov.in/"
  },
  {
    id: "karnataka-farm-mechanisation",
    category: "State",
    state: "Karnataka",
    lastUpdated: "2024-03-10",
    contact: {
      department: "Department of Agriculture, Karnataka",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Karnataka+Farm+Mechanisation+Programme"
  },
  {
    id: "karnataka-surya-raitha",
    category: "State",
    state: "Karnataka",
    lastUpdated: "2024-05-15",
    contact: {
      department: "Department of Energy and Agriculture, Karnataka",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Karnataka+Surya+Raitha+Scheme"
  },
  {
    id: "kerala-smam",
    category: "State",
    state: "Kerala",
    lastUpdated: "2023-12-15",
    contact: {
      department: "Department of Agriculture, Kerala",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Sub-Mission+on+Agricultural+Mechanisation+Kerala"
  },
  {
    id: "kerala-karshaka-pension",
    category: "State",
    state: "Kerala",
    lastUpdated: "2025-05-17",
    contact: {
      department: "Department of Agriculture, Kerala",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Karshaka+Pension+Scheme+Kerala"
  },
  {
    id: "mp-cmkgy",
    category: "State",
    state: "Madhya Pradesh",
    lastUpdated: "2024-04-01",
    contact: {
      department: "Dept. of Agriculture & Rural Development, MP",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Chief+Minister+Agriculture+and+Rural+Development+Scheme+Madhya+Pradesh"
  },
  {
    id: "mp-kbby",
    category: "State",
    state: "Madhya Pradesh",
    lastUpdated: "2023-07-01",
    contact: {
      department: "Dept. of Agriculture, MP",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Krishi+Bandhu+Bima+Yojana+Madhya+Pradesh"
  },
  {
    id: "mp-bhavantar-bhugtan",
    category: "State",
    state: "Madhya Pradesh",
    lastUpdated: "2023-10-01",
    contact: {
      department: "Dept. of Agriculture, MP",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Bhavantar+Bhugtan+Yojana+Madhya+Pradesh"
  },
  {
    id: "mp-goat-farming",
    category: "State",
    state: "Madhya Pradesh",
    lastUpdated: "2025-04-01",
    contact: {
      department: "Dept. of Animal Husbandry, MP",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Goat+Farming+Subsidy+Scheme+Madhya+Pradesh"
  },
  {
    id: "mp-pkvy",
    category: "State",
    state: "Madhya Pradesh",
    lastUpdated: "2022-12-01",
    contact: {
      department: "Dept. of Agriculture, MP",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Paramparagat+Krishi+Vikas+Yojana+Madhya+Pradesh"
  },
  {
    id: "manipur-orchards-floriculture",
    category: "State",
    state: "Manipur",
    lastUpdated: "2024-01-01",
    contact: {
      department: "Department of Horticulture & Soil Conservation, Manipur",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Assistance+for+Orchards+Floriculture+Manipur"
  },
  {
    id: "manipur-micro-irrigation",
    category: "State",
    state: "Manipur",
    lastUpdated: "2020-11-11",
    contact: {
      department: "Department of Agriculture, Manipur",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Micro-Irrigation+Subsidy+Manipur"
  },
  {
    id: "manipur-fruit-wadi",
    category: "State",
    state: "Manipur",
    lastUpdated: "2021-03-01",
    contact: {
      department: "Department of Agriculture, Manipur",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Fruit-Wadi+Scheme+Manipur"
  },
  {
    id: "meghalaya-agri-machinery",
    category: "State",
    state: "Meghalaya",
    lastUpdated: "2025-06-06",
    contact: {
      department: "Department of Agriculture & Farmers’ Welfare, Meghalaya",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Supply+of+Agricultural+Machinery+Meghalaya"
  },
  {
    id: "meghalaya-vegetable-dev",
    category: "State",
    state: "Meghalaya",
    lastUpdated: "2025-04-01",
    contact: {
      department: "Department of Agriculture & Farmers’ Welfare, Meghalaya",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Vegetable+Development+Scheme+Meghalaya"
  },
  {
    id: "meghalaya-hmneh",
    category: "State",
    state: "Meghalaya",
    lastUpdated: "2025-05-06",
    contact: {
      department: "Dept. of Agriculture & Farmers’ Welfare, Meghalaya",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=HMNEH+Horticulture+Mission+Meghalaya"
  },
  {
    id: "meghalaya-prime-arv",
    category: "State",
    state: "Meghalaya",
    lastUpdated: "2025-05-10",
    contact: {
      department: "PRIME Agricultural Development Unit",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=PRIME+ARV+Scheme+Meghalaya"
  },
  {
    id: "mizoram-bana-kaih",
    category: "State",
    state: "Mizoram",
    lastUpdated: "2025-05-15",
    contact: {
      department: "Mizoram Agriculture Marketing Board & Rural Development Department",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Bana+Kaih+Scheme+Mizoram"
  },
  {
    id: "mizoram-pkvy-movcd-ner",
    category: "State",
    state: "Mizoram",
    lastUpdated: "2023-03-01",
    contact: {
      department: "Department of Agriculture & Farmers’ Welfare, Mizoram",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=MOVCD-NER+Mizoram"
  },
  {
    id: "mizoram-vksa",
    category: "State",
    state: "Mizoram",
    lastUpdated: "2025-06-05",
    contact: {
      department: "Department of Agriculture & Farmers’ Welfare, Mizoram",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Viksit+Krishi+Sankalp+Abhiyan+Mizoram"
  },
  {
    id: "mizoram-movcd-ner",
    category: "State",
    state: "Mizoram",
    lastUpdated: "2023-01-01",
    contact: {
      department: "Department of Agriculture & Farmers’ Welfare, Mizoram",
      phone: "--",
      email: "--"
    },
    website: "https://movcdner.dac.gov.in/"
  },
  {
    id: "nagaland-smam",
    category: "State",
    state: "Nagaland",
    lastUpdated: "2023‑2024",
    contact: {
      department: "Department of Agriculture, Nagaland",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=SMAM+Farm+Mechanisation+Subsidy+Nagaland"
  },
  {
    id: "nagaland-focus",
    category: "State",
    state: "Nagaland",
    lastUpdated: "March 2024",
    contact: {
      department: "Agriculture Production Commissioner Office, Nagaland",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=FOCUS+Climate+Resilient+Upland+Farming+Nagaland"
  },
  {
    id: "nagaland-oil-palm",
    category: "State",
    state: "Nagaland",
    lastUpdated: "2023‑01‑01",
    contact: {
      department: "Department of Agriculture, Nagaland",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Oil‑palm+Cultivation+Promotion+Nagaland"
  },
  {
    id: "odisha-cm-kisan",
    category: "State",
    state: "Odisha",
    lastUpdated: "2025‑Nuakhai cycle",
    contact: {
      department: "Dept. of Agriculture & Farmers Empowerment, Odisha",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=CM+KISAN+Yojana+Odisha"
  },
  {
    id: "punjab-maize-diversification",
    category: "State",
    state: "Punjab",
    lastUpdated: "June 2025",
    contact: {
      department: "Dept. of Agriculture, Punjab",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Maize+Diversification+Incentive+Punjab"
  },
  {
    id: "punjab-seed-cotton-subsidy",
    category: "State",
    state: "Punjab",
    lastUpdated: "2025 Kharif",
    contact: {
      department: "Dept. of Agriculture, Punjab",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Punjab+Seed+Cotton+Subsidy+Scheme"
  },
  {
    id: "punjab-crop-residue-management",
    category: "State",
    state: "Punjab",
    lastUpdated: "2025–26",
    contact: {
      department: "Dept. of Agriculture, Punjab",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Crop+Residue+Management+Subsidy+Punjab"
  },
  {
    id: "punjab-aif",
    category: "State",
    state: "Punjab",
    lastUpdated: "June 2024",
    contact: {
      department: "Dept. of Horticulture, Punjab",
      phone: "--",
      email: "--"
    },
    website: "https://agriinfra.dac.gov.in/"
  },
  {
    id: "rajasthan-naye-fal-bagecho",
    category: "State",
    state: "Rajasthan",
    lastUpdated: "2025-05-15",
    contact: {
      department: "Department of Horticulture, Rajasthan",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Naye+Fal+Bagecho+Ki+Sthapana+Rajasthan"
  },
  {
    id: "rajasthan-kantedar-tarbandi",
    category: "State",
    state: "Rajasthan",
    lastUpdated: "2025-05-01",
    contact: {
      department: "Department of Agriculture, Rajasthan",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Kantedar+Tarbandi+Yojana+Rajasthan"
  },
  {
    id: "rajasthan-pm-kusum",
    category: "State",
    state: "Rajasthan",
    lastUpdated: "2025-05-10",
    contact: {
      department: "DISCOM, Energy Department, Rajasthan",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=PM-KUSUM+Solar+Pump+Scheme+Rajasthan"
  },
  {
    id: "rajasthan-loan-waiver-2018",
    category: "State",
    state: "Rajasthan",
    lastUpdated: "2018-02-01",
    contact: {
      department: "Department of Finance, Rajasthan",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=One-Time+Farm+Loan+Waiver+2018+Rajasthan"
  },
  {
    id: "sikkim-organic-mission",
    category: "State",
    state: "Sikkim",
    lastUpdated: "2024-12-01",
    contact: {
      department: "Department of Agriculture, Sikkim",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Sikkim+Organic+Mission"
  },
  {
    id: "sikkim-minor-irrigation",
    category: "State",
    state: "Sikkim",
    lastUpdated: "2023-11-15",
    contact: {
      department: "Water Resources Department, Sikkim",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Minor+Irrigation+via+Gravity+Schemes+Sikkim"
  },
  {
    id: "tn-drip-irrigation",
    category: "State",
    state: "Tamil Nadu",
    lastUpdated: "2024-",
    contact: {
      department: "Dept. of Agriculture, TN",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Drip+Irrigation+Subsidy+Tamil+Nadu"
  },
  {
    id: "tn-animal-husbandry",
    category: "State",
    state: "Tamil Nadu",
    lastUpdated: "2023-",
    contact: {
      department: "Dept. of Animal Husbandry, TN",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Animal+Husbandry+Asset+Development+Tamil+Nadu"
  },
  {
    id: "tripura-vksa",
    category: "State",
    state: "Tripura",
    lastUpdated: "2025-06-12",
    contact: {
      department: "Dept. of Agriculture & Farmers’ Welfare, Tripura",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Viksit+Krishi+Sankalp+Abhiyan+Tripura"
  },
  {
    id: "tripura-smam",
    category: "State",
    state: "Tripura",
    lastUpdated: "2024-",
    contact: {
      department: "Dept. of Agriculture & Farmers’ Welfare, Tripura",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=SMAM+Tripura"
  },
  {
    id: "uttarakhand-smam",
    category: "State",
    state: "Uttarakhand",
    lastUpdated: "2024-11-14",
    contact: {
      department: "Department of Agriculture, Uttarakhand",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=SMAM+Uttarakhand"
  },
  {
    id: "uttarakhand-maun-palan",
    category: "State",
    state: "Uttarakhand",
    lastUpdated: "2025-?",
    contact: {
      department: "State Horticulture Mission, Uttarakhand",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Maun+Palan+Uttarakhand"
  },
  {
    id: "uttarakhand-pkvy",
    category: "State",
    state: "Uttarakhand",
    lastUpdated: "2025‑04",
    contact: {
      department: "Department of Agriculture, Uttarakhand",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=PKVY+Uttarakhand"
  },
  {
    id: "up-krishak-samriddhi",
    category: "State",
    state: "Uttar Pradesh",
    lastUpdated: "2025-05",
    contact: {
      department: "UP Cooperative and Agriculture Dept.",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Mukhyamantri+Krishak+Samriddhi+Yojana+UP"
  },
  {
    id: "up-pragati",
    category: "State",
    state: "Uttar Pradesh",
    lastUpdated: "2025-",
    contact: {
      department: "UP Agri Dept & 2030 WRG Platform",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=PRAGATI+Agri‑Water‑Use+Efficiency+Accelerator+UP"
  },
  {
    id: "up-in-situ-crm",
    category: "State",
    state: "Uttar Pradesh",
    lastUpdated: "2025‑06",
    contact: {
      department: "UP Agriculture Department",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=In‑Situ+Crop+Residue+Management+UP"
  },
  {
    id: "up-tubewell-modernisation",
    category: "State",
    state: "Uttar Pradesh",
    lastUpdated: "Plan 2025‑27",
    contact: {
      department: "UP Water Conservation Dept.",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Eco‑Friendly+Tubewell+Modernisation+UP"
  },
  {
    id: "wb-ota-sfi",
    category: "State",
    state: "West Bengal",
    lastUpdated: "2025‑04",
    contact: {
      department: "West Bengal Dept. of Agriculture",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=OTA‑SFI+West+Bengal"
  },
  {
    id: "andaman-agri-inputs",
    category: "State",
    state: "Andaman and Nicobar Islands",
    lastUpdated: "2024-06-11",
    contact: {
      department: "Department of Agriculture, Andaman and Nicobar Islands",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Subsidies+on+Various+Agriculture+Inputs+Andaman+and+Nicobar+Islands"
  },
  {
    id: "andaman-ponds-pumpsets",
    category: "State",
    state: "Andaman and Nicobar Islands",
    lastUpdated: "2024-06-11",
    contact: {
      department: "Department of Agriculture, Andaman and Nicobar Islands",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Subsidy+for+Ponds+and+Pumpsets+Andaman+and+Nicobar+Islands"
  },
  {
    id: "andaman-coconut-mission",
    category: "State",
    state: "Andaman and Nicobar Islands",
    lastUpdated: "2024-06-11",
    contact: {
      department: "Department of Agriculture, Andaman and Nicobar Islands",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Technology+Mission+on+Development+of+Coconut+Andaman+and+Nicobar+Islands"
  },
  {
    id: "puducherry-agri-mechanisation",
    category: "State",
    state: "Puducherry",
    lastUpdated: "2025-03-26",
    contact: {
      department: "Department of Agriculture and Farmer's Welfare, Puducherry",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Agricultural+Mechanisation+Support+Puducherry"
  },
  {
    id: "puducherry-paddy-incentives",
    category: "State",
    state: "Puducherry",
    lastUpdated: "2025-03-26",
    contact: {
      department: "Department of Agriculture and Farmer's Welfare, Puducherry",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Incentives+for+Paddy+Cultivation+Puducherry"
  },
  {
    id: "puducherry-fodder-subsidy",
    category: "State",
    state: "Puducherry",
    lastUpdated: "2024-06-11",
    contact: {
      department: "Department of Agriculture and Farmer's Welfare, Puducherry",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Subsidy+for+Cultivation+of+Fodder+Crops+Puducherry"
  },
  {
    id: "lakshadweep-organic-farming",
    category: "State",
    state: "Lakshadweep",
    lastUpdated: "2025-06-05",
    contact: {
      department: "Department of Agriculture, UT Administration of Lakshadweep",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Organic+Farming+Lakshadweep"
  },
  {
    id: "lakshadweep-coconut-friends",
    category: "State",
    state: "Lakshadweep",
    lastUpdated: "2025-06-05",
    contact: {
      department: "Department of Agriculture, UT Administration of Lakshadweep / ICAR-CMFRI Lakshadweep Krishi Vigyan Kendra (KVK)",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Friends+of+Coconut+Initiative+Lakshadweep"
  },
  {
    id: "lakshadweep-veg-fruit-promo",
    category: "State",
    state: "Lakshadweep",
    lastUpdated: "2025-06-05",
    contact: {
      department: "Department of Agriculture, UT Administration of Lakshadweep / ICAR-CMFRI Lakshadweep Krishi Vigyan Kendra (KVK)",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Vegetable+and+Fruit+Cultivation+Lakshadweep"
  },
  {
    id: "delhi-agri-inputs",
    category: "State",
    state: "Delhi",
    lastUpdated: "2024-06-11",
    contact: {
      department: "Department of Agriculture, Delhi",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Agricultural+support+Delhi"
  },
  {
    id: "chandigarh-agri-inputs",
    category: "State",
    state: "Chandigarh",
    lastUpdated: "2021-09-14",
    contact: {
      department: "Agriculture Department, Chandigarh",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Agricultural+support+Chandigarh"
  },
  {
    id: "dnh-dd-seed-dist",
    category: "State",
    state: "Dadra and Nagar Haveli and Daman and Diu",
    lastUpdated: "2025-02-03",
    contact: {
      department: "Agriculture Department, Dadra and Nagar Haveli and Daman and Diu",
      phone: "0260-2230856",
      email: "--"
    },
    website: "https://www.google.com/search?q=Distribution+of+Agriculture+Seeds+Daman"
  },
  {
    id: "dnh-dd-bee-keeping",
    category: "State",
    state: "Dadra and Nagar Haveli and Daman and Diu",
    lastUpdated: "2019-03-08",
    contact: {
      department: "Agriculture Department, Dadra and Nagar Haveli and Daman and Diu",
      phone: "0260-2230856",
      email: "--"
    },
    website: "https://www.google.com/search?q=Bee+Keeping+Daman+Diu"
  },
  {
    id: "jk-hadp",
    category: "State",
    state: "Jammu and Kashmir",
    lastUpdated: "2025-02-21",
    contact: {
      department: "Department of Agriculture, Jammu and Kashmir",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Holistic+Agriculture+Development+Program+Jammu+and+Kashmir"
  },
  {
    id: "ladakh-agri-dev",
    category: "State",
    state: "Ladakh",
    lastUpdated: "2025-06-04",
    contact: {
      department: "Agriculture Department, UT Ladakh",
      phone: "--",
      email: "--"
    },
    website: "https://www.google.com/search?q=Agricultural+Development+Ladakh"
  }
];
